version: 2
jobs:
  release:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/kpn/mq-hammer
    steps:
      - checkout
      - run: make bootstrap
      - run: make test
      - run: make github_release
  release-docker:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/kpn/mq-hammer
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make bootstrap
      - run: make test
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: make docker_release
  test:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/kpn/mq-hammer
    steps:
      - checkout
      - run: make bootstrap
      - run: make test
workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/
  test:
    jobs:
      - test
  release-docker:
    jobs:
      - release-docker:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/
